# Generated by Django 5.0.2 on 2024-02-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_users_options_users_geo_alter_users_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'пользователь телеграмм', 'verbose_name_plural': 'Пользователи тг'},
        ),
        migrations.AddField(
            model_name='users',
            name='image_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
