# Generated by Django 5.0.2 on 2024-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_users_options_users_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_premium',
            field=models.BooleanField(blank=True, null=True, verbose_name='Премиум'),
        ),
        migrations.AddField(
            model_name='users',
            name='language_code',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Язык'),
        ),
    ]
