# Generated by Django 5.0.2 on 2024-02-14 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_users_is_premium_users_language_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='image_id',
            new_name='image_path',
        ),
    ]
